name = "password-purgatory-logger"
main = "index.js"

workers_dev = true
compatibility_date = "2022-07-24"

kv_namespaces = [
         { binding = "PASSWORD_PURGATORY", id = "b2e505e33ddb4cc5ae3672efc57e7e9d", preview_id = "b2e505e33ddb4cc5ae3672efc57e7e9d" }
]
